### ISSUE TITLE
Filtering works incorrectly for `in`/`notin` strings with the comma

### ISSUE THREAD

**Issue by roland-chernov-akvelon** [nestjsx/crud#86]
Hi, Thank you for the great library!

Recently I ran into a problem with array value filters (`in`/`notin`). I'd like to filter rows which may contain "," but the comma is used as values delimiter so I'm getting an empty result.

Please check [this test](https://github.com/nestjsx/crud/compare/master...roland-chernov-akvelon:array-filters-delimeter-issue) for details.

It seems strings escaping isn't supported, please correct me if I'm wrong. I wonder if there is a way to workaround this issue.

Thanks,
Roland

**Comment by roland-chernov-akvelon** [comment]
I'm not sure but maybe related to #49.

**Comment by zMotivat0r** [comment]
@roland-chernov-akvelon yep.
I'm working on a version 4 with a lot of stuff refactored and changed, so I might be slow with response :(

**Comment by roland-chernov-akvelon** [comment]
No problem. I just didn't notice that this issue was already fixed. Thanks!

**Comment by denodaeus** [comment]
I'm still experiencing this on 5.0.0 -- is there a way to pass in a filter in the API calls that has commas?  I tried wrapping the value in quotes:

valid||$in||"Latest CEP used, BestEx Returned"
